var = input('Digite algo: ')
print(type(var))
print('É um número alfanúmerico?', var.isalnum())
print('É um digito?', var.isdigit())
print('É um decimal?', var.isdecimal())
print('É um número', var.isnumeric())
