var = int(input('Digite um número: '))
print(('Tabuada do {}'.format(var)))
print('{} * 1 = {}'.format(var, var * 1))
print('{} * 2 = {}'.format(var, var * 2))
print('{} * 3 = {}'.format(var, var * 3))
print('{} * 4 = {}'.format(var, var * 4))
print('{} * 5 = {}'.format(var, var * 5))
print('{} * 6 = {}'.format(var, var * 6))
print('{} * 7 = {}'.format(var, var * 7))
print('{} * 8 = {}'.format(var, var * 8))
print('{} * 9 = {}'.format(var, var * 9))
print('{} * 10 = {}'.format(var, var * 10))
