nome = str(input('Digite o seu nome: '))
print('Analisando seu nome...')
print('Seu nome em maíúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
listaNome = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(listaNome[0], len(listaNome[0])))
